# Generated by Django 5.0.3 on 2024-04-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buybay_logic', '0003_user_delete_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='client',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
