# Generated by Django 5.0.3 on 2024-04-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buybay_logic', '0004_rename_user_client_alter_client_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False},
        ),
    ]
