# Generated by Django 5.0.3 on 2024-04-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybay_logic', '0006_accessory_car_clothing_home_appliance_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('mileage', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('finition', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=10)),
                ('fuel', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('des', models.CharField(max_length=1000)),
                ('image', models.BinaryField()),
                ('id_client', models.ForeignKey('Client', on_delete=models.CASCADE))
            ],
            options={
                'db_table': 'buybay_logic_car',
                'managed': False,
            },
        ),
    ]
