# Generated by Django 5.0.3 on 2024-04-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybay_logic', '0007_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'buybay_logic_moderator',
                'managed': False,
            },
        ),
    ]
